test for failure before copying to testbed

diff --git a/apps/breakfast/bacon/Leaf/burn b/apps/breakfast/bacon/Leaf/burn
--- a/apps/breakfast/bacon/Leaf/burn
+++ b/apps/breakfast/bacon/Leaf/burn
@@ -9,7 +9,13 @@ shift 1
 
 make bacon2 $@
 
-for i in $(grep -v '#' $MAP | awk '{print $2}')
-do
-  make bacon2 reinstall,$i wpt,$MAP
-done
+if [ $? -eq 0 ]
+then
+  for i in $(grep -v '#' $MAP | awk '{print $2}')
+  do
+    make bacon2 reinstall,$i wpt,$MAP
+  done
+else
+  echo "BUILD FAILED"
+  exit 1
+fi
